import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        popover: "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        destructive: "var(--destructive)",
        "destructive-foreground": "var(--destructive-foreground)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        
        // Custom App Colors
        "on-surface": "#181d19",
        "surface-container-highest": "#e0e3de",
        "secondary-fixed": "#ffdad2",
        "surface-bright": "#f7faf5",
        "on-surface-variant": "#3f4942",
        "surface-container-low": "#f1f5ef",
        "on-error-container": "#93000a",
        "tertiary": "#753136",
        "on-primary-fixed-variant": "#005232",
        "surface-container-high": "#e6e9e4",
        "primary-fixed": "#a7f3c5",
        "on-tertiary-container": "#ffcccd",
        "surface-container": "#ecefe9",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#3c0700",
        "outline": "#707a71",
        "error-container": "#ffdad6",
        "outline-variant": "#bfc9c0",
        "on-primary": "#ffffff",
        "primary": "#005232",
        "surface-tint": "#1e6b47",
        "primary-fixed-dim": "#8bd6aa",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2d312e",
        "on-tertiary-fixed": "#3c060e",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-background": "#181d19",
        "surface-variant": "#e0e3de",
        "on-secondary-container": "#661300",
        "primary-container": "#1e6b47",
        "secondary-container": "#ff6e49",
        "surface-dim": "#d8dbd6",
        "secondary": "#ad3313",
        "tertiary-container": "#92484c",
        "on-primary-container": "#9de9bb",
        "inverse-primary": "#8bd6aa",
        "tertiary-fixed": "#ffdada",
        "on-primary-fixed": "#002111",
        "on-secondary-fixed-variant": "#891d00",
        "secondary-fixed-dim": "#ffb4a2",
        "inverse-on-surface": "#eef2ec",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#ffb3b4",
        "on-tertiary-fixed-variant": "#753136",
        "surface": "#f7faf5"
      },
      borderRadius: {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      spacing: {
          "md": "16px",
          "xs": "4px",
          "margin": "24px",
          "xl": "32px",
          "lg": "24px",
          "sm": "8px",
          "base": "4px",
          "gutter": "16px"
      },
      fontFamily: {
          "body-base": ["var(--font-inter)", "sans-serif"],
          "label-caps": ["var(--font-inter)", "sans-serif"],
          "headline-md": ["var(--font-inter)", "sans-serif"],
          "body-sm": ["var(--font-inter)", "sans-serif"],
          "button": ["var(--font-inter)", "sans-serif"],
          "display-lg": ["var(--font-inter)", "sans-serif"],
          "title-sm": ["var(--font-inter)", "sans-serif"]
      },
      fontSize: {
          "body-base": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
          "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
          "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
          "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
          "button": ["15px", { "lineHeight": "20px", "fontWeight": "600" }],
          "display-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
          "title-sm": ["18px", { "lineHeight": "24px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
};
export default config;
